# Generated by Django 3.1.2 on 2020-12-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='technology_tag',
            field=models.CharField(choices=[('Data Science', 'Data Science'), ('Computer Science', 'Computer Science'), ('FrontEnd', 'FrontEnd'), ('BackEnd', 'BackEnd'), ('UI/UX', 'UI/UX'), ('English', 'English')], max_length=60, null=True),
        ),
    ]
