# Generated by Django 3.1.2 on 2020-12-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20201219_0533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technologie',
        ),
    ]
