# Generated by Django 3.1.2 on 2020-12-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_delete_technologie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
